/**
 * REELIX — Shared Caption Style System
 *
 * Single source of truth for template presets and the CSS each style produces.
 * The template picker thumbnails, the live video overlay and the backend
 * exporter all read from here so what you see is what gets burned in.
 */

import { NEGATIVE_DEFAULTS } from './negativeText';
import fontLibrary from './fontLibrary.json';

/**
 * Every caption font on disk, generated from the actual files by
 * backend/tools/sync_fonts.py: { family, category, tagline, weights, italics, defaultWeight }.
 */
export const FONT_LIBRARY = fontLibrary.fonts;
export const FONT_CATEGORIES = Object.entries(fontLibrary.categories).map(([id, label]) => ({ id, label }));
export const WEIGHT_LABELS = { 100: 'Thin', 200: 'ExtraLight', 300: 'Light', 400: 'Regular', 500: 'Medium', 600: 'SemiBold', 700: 'Bold', 800: 'ExtraBold', 900: 'Black' };

export function fontInfo(family) {
  return FONT_LIBRARY.find((f) => f.family === family) || null;
}

/** Nearest weight the family actually ships (ties go heavier) — the export picks the same file. */
export function nearestFontWeight(family, weight) {
  const info = fontInfo(family);
  if (!info || !info.weights.length) return weight || 900;
  const target = Number(weight) || 900;
  return info.weights.reduce((best, w) => {
    const d = Math.abs(w - target);
    const bd = Math.abs(best - target);
    return d < bd || (d === bd && w > best) ? w : best;
  }, info.weights[0]);
}

/** CSS font shorthand for canvas measurement / drawing, matching the DOM caption. */
export function captionFontString(style, px) {
  const weight = nearestFontWeight(style.fontFamily, style.fontWeight);
  return `${style.italic ? 'italic ' : ''}${weight} ${Math.max(1, Math.floor(px))}px "${style.fontFamily || 'Montserrat'}"`;
}

export const TEMPLATE_CATEGORIES = [
  { id: 'premium', label: 'Premium Reels', hint: 'Instagram-grade type: heavy grotesks, true Black weights and editorial serifs' },
  { id: 'karaoke', label: 'Kalakar Karaoke', hint: 'Word-by-word box highlight that follows the voice' },
  { id: 'viral', label: 'Viral Reels', hint: 'High-contrast punch styles built for IG / TikTok' },
  { id: 'aesthetic', label: 'Pinterest Aesthetic', hint: 'Editorial, serif and soft minimal typography' },
  { id: 'blend', label: 'Inverted & Experimental', hint: 'Pixel-blend and cutout treatments' },
];

const BASE = {
  // 'dom' = CSS overlay + LibASS/difference export. 'negative' = the Canvas2D /
  // numpy Negative Text pipeline (see negativeText.js). Every template sets it
  // so switching templates never leaves a stale renderer behind.
  renderer: 'dom',
  fontWeight: 900,     // resolved to the nearest weight the family ships (see nearestFontWeight)
  fontSize: 30,
  xPercent: 50,
  yPercent: 82,
  position: 'bottom',
  color: '#ffffff',
  backgroundColor: 'transparent',
  strokeColor: '#000000',
  shadowColor: '#000000',
  mixBlendMode: 'normal',
  flipH: false,
  italic: false,
  borderStyle: 1,
  textTransform: 'uppercase',
  letterSpacing: 0,
  lineHeight: 1.05,
  maxWordsPerLine: 3,
  highlightMode: 'color',
  highlightBg: '#facc15',
  highlightTextColor: '#0b0b0b',
  karaoke: true,
  activeScale: 1.14,
  bgPadding: 0,
  bgRadius: 0,
  transition: 'Fade In + Slide Up',
};

export const TEMPLATE_PRESETS = [
  // ───────────────────────────── Premium Reels ─────────────────────────────
  {
    ...BASE,
    id: 'premium_poppins_punch',
    category: 'premium',
    name: 'Poppins Black Punch',
    fontFamily: 'Poppins',
    fontWeight: 900,
    fontSize: 32,
    highlightColor: '#facc15',
    highlightMode: 'color',
    strokeWidth: 4,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    activeScale: 1.16,
    letterSpacing: -0.5,
    maxWordsPerLine: 3,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'premium_archivo_box',
    category: 'premium',
    name: 'Archivo Headline Box',
    fontFamily: 'Archivo Black',
    fontWeight: 400,
    fontSize: 30,
    highlightColor: '#0b0b0b',
    highlightMode: 'box',
    highlightBg: '#ffffff',
    highlightTextColor: '#0b0b0b',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.85,
    shadowDistance: 4,
    activeScale: 1.08,
    maxWordsPerLine: 3,
    bgRadius: 6,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'premium_dela_impact',
    category: 'premium',
    name: 'Dela Gothic Impact',
    fontFamily: 'Dela Gothic One',
    fontWeight: 400,
    fontSize: 28,
    highlightColor: '#ff3b3b',
    highlightMode: 'color',
    strokeWidth: 3,
    shadowType: 'hard',
    shadowBlur: 0,
    shadowOpacity: 1,
    shadowDistance: 5,
    shadowColor: '#111111',
    activeScale: 1.12,
    letterSpacing: 0.5,
    maxWordsPerLine: 3,
    transition: 'Zoom Kinetic',
  },
  {
    ...BASE,
    id: 'premium_kanit_lime',
    category: 'premium',
    name: 'Kanit Lime Karaoke',
    fontFamily: 'Kanit',
    fontWeight: 900,
    fontSize: 32,
    highlightColor: '#0b0b0b',
    highlightMode: 'box',
    highlightBg: '#a3e635',
    highlightTextColor: '#0b0b0b',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.85,
    shadowDistance: 4,
    activeScale: 1.1,
    maxWordsPerLine: 3,
    bgRadius: 10,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'premium_league_wide',
    category: 'premium',
    name: 'League Spartan Wide',
    fontFamily: 'League Spartan',
    fontWeight: 900,
    fontSize: 30,
    highlightColor: '#f97316',
    highlightMode: 'color',
    strokeWidth: 2.5,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    activeScale: 1.14,
    letterSpacing: 2,
    maxWordsPerLine: 3,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'premium_unbounded_future',
    category: 'premium',
    name: 'Unbounded Future',
    fontFamily: 'Unbounded',
    fontWeight: 800,
    fontSize: 24,
    color: '#f8fafc',
    highlightColor: '#22d3ee',
    highlightMode: 'underline',
    highlightBg: '#22d3ee',
    strokeWidth: 0,
    shadowType: 'glow',
    shadowBlur: 18,
    shadowOpacity: 0.6,
    shadowDistance: 0,
    shadowColor: '#22d3ee',
    activeScale: 1.06,
    letterSpacing: 1,
    lineHeight: 1.15,
    maxWordsPerLine: 3,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'premium_lilita_pop',
    category: 'premium',
    name: 'Lilita Candy Pop',
    fontFamily: 'Lilita One',
    fontWeight: 400,
    fontSize: 32,
    highlightColor: '#ffffff',
    highlightMode: 'box',
    highlightBg: '#ff2bd6',
    highlightTextColor: '#ffffff',
    strokeWidth: 3.5,
    strokeColor: '#1a0b2e',
    shadowType: 'hard',
    shadowBlur: 0,
    shadowOpacity: 1,
    shadowDistance: 5,
    shadowColor: '#1a0b2e',
    activeScale: 1.12,
    maxWordsPerLine: 3,
    bgRadius: 12,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'premium_space_tech',
    category: 'premium',
    name: 'Space Grotesk Tech',
    fontFamily: 'Space Grotesk',
    fontWeight: 700,
    fontSize: 26,
    highlightColor: '#0f172a',
    highlightMode: 'box',
    highlightBg: '#e2e8f0',
    highlightTextColor: '#0f172a',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 12,
    shadowOpacity: 0.7,
    shadowDistance: 3,
    activeScale: 1.06,
    letterSpacing: 1.5,
    maxWordsPerLine: 3,
    bgRadius: 2,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'premium_satoshi_pill',
    category: 'premium',
    name: 'Satoshi White Pill',
    fontFamily: 'Satoshi',
    fontWeight: 900,
    fontSize: 22,
    color: '#0b0b0b',
    highlightColor: '#0b0b0b',
    highlightMode: 'none',
    backgroundColor: '#ffffff',
    borderStyle: 3,
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 18,
    shadowOpacity: 0.35,
    shadowDistance: 4,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    lineHeight: 1.25,
    maxWordsPerLine: 5,
    bgPadding: 12,
    bgRadius: 14,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_clash_editorial',
    category: 'premium',
    name: 'Clash Editorial',
    fontFamily: 'Clash Display',
    fontWeight: 600,
    fontSize: 30,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 20,
    shadowOpacity: 0.5,
    shadowDistance: 4,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    letterSpacing: -0.5,
    lineHeight: 1.1,
    maxWordsPerLine: 4,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_instrument_aesthetic',
    category: 'premium',
    name: 'Instrument Serif Aesthetic',
    fontFamily: 'Instrument Serif',
    fontWeight: 400,
    italic: true,
    fontSize: 36,
    color: '#fffdf7',
    highlightColor: '#fffdf7',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 18,
    shadowOpacity: 0.45,
    shadowDistance: 3,
    textTransform: 'lowercase',
    karaoke: false,
    activeScale: 1,
    lineHeight: 1.05,
    maxWordsPerLine: 4,
    yPercent: 50,
    position: 'center',
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_dm_serif_quote',
    category: 'premium',
    name: 'DM Serif Quote',
    fontFamily: 'DM Serif Display',
    fontWeight: 400,
    fontSize: 30,
    color: '#ffffff',
    highlightColor: '#f7e7b4',
    highlightMode: 'color',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.5,
    shadowDistance: 3,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    lineHeight: 1.15,
    maxWordsPerLine: 4,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_cormorant_whisper',
    category: 'premium',
    name: 'Cormorant Whisper',
    fontFamily: 'Cormorant Garamond',
    fontWeight: 600,
    italic: true,
    fontSize: 36,
    color: '#fffdf7',
    highlightColor: '#fffdf7',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.4,
    shadowDistance: 2,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    letterSpacing: 0.5,
    lineHeight: 1.1,
    maxWordsPerLine: 4,
    yPercent: 50,
    position: 'center',
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_bodoni_vogue',
    category: 'premium',
    name: 'Bodoni Vogue',
    fontFamily: 'Bodoni Moda',
    fontWeight: 700,
    fontSize: 30,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.5,
    shadowDistance: 3,
    karaoke: false,
    activeScale: 1,
    letterSpacing: 4,
    lineHeight: 1.2,
    maxWordsPerLine: 3,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'premium_italiana_couture',
    category: 'premium',
    name: 'Italiana Couture',
    fontFamily: 'Italiana',
    fontWeight: 400,
    fontSize: 36,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 12,
    shadowOpacity: 0.4,
    shadowDistance: 2,
    karaoke: false,
    activeScale: 1,
    letterSpacing: 6,
    lineHeight: 1.3,
    maxWordsPerLine: 3,
    transition: 'Fade In',
  },

  // ─────────────────────────── Kalakar Karaoke ───────────────────────────
  {
    ...BASE,
    id: 'kalakar_gold',
    category: 'karaoke',
    name: 'Kalakar Signature Gold',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 32,
    highlightColor: '#0b0b0b',
    highlightMode: 'box',
    highlightBg: '#ffd60a',
    highlightTextColor: '#0b0b0b',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.85,
    shadowDistance: 4,
    maxWordsPerLine: 3,
    bgRadius: 8,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'kalakar_lime',
    category: 'karaoke',
    name: 'Kalakar Neon Lime',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 32,
    highlightColor: '#0b0b0b',
    highlightMode: 'box',
    highlightBg: '#39ff14',
    highlightTextColor: '#0b0b0b',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 18,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    maxWordsPerLine: 3,
    bgRadius: 8,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'kalakar_blood',
    category: 'karaoke',
    name: 'Kalakar Blood Red',
    fontFamily: 'Bebas Neue',
    fontWeight: 400,
    fontSize: 36,
    highlightColor: '#ffffff',
    highlightMode: 'box',
    highlightBg: '#e11d48',
    highlightTextColor: '#ffffff',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    letterSpacing: 1,
    maxWordsPerLine: 3,
    bgRadius: 6,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'kalakar_electric',
    category: 'karaoke',
    name: 'Kalakar Electric Violet',
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 30,
    highlightColor: '#ffffff',
    highlightMode: 'box',
    highlightBg: '#7c3aed',
    highlightTextColor: '#ffffff',
    strokeWidth: 1.5,
    shadowType: 'glow',
    shadowBlur: 18,
    shadowOpacity: 0.7,
    shadowDistance: 0,
    maxWordsPerLine: 3,
    bgRadius: 10,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'karaoke_underline',
    category: 'karaoke',
    name: 'Spoken Word Underline',
    fontFamily: 'Plus Jakarta Sans',
    fontWeight: 800,
    fontSize: 28,
    highlightColor: '#22d3ee',
    highlightMode: 'underline',
    highlightBg: '#22d3ee',
    strokeWidth: 2,
    shadowType: 'cinematic',
    shadowBlur: 12,
    shadowOpacity: 0.85,
    shadowDistance: 3,
    maxWordsPerLine: 4,
    transition: 'Fade In + Slide Up',
  },

  // ───────────────────────────── Viral Reels ─────────────────────────────
  {
    ...BASE,
    id: 'hormozi_punch',
    category: 'viral',
    name: 'Hormozi Viral Punch',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 34,
    highlightColor: '#facc15',
    highlightMode: 'color',
    strokeWidth: 5,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.95,
    shadowDistance: 5,
    activeScale: 1.2,
    maxWordsPerLine: 3,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'beast_bold',
    category: 'viral',
    name: 'MrBeast Bold Pop',
    fontFamily: 'Rubik',
    fontWeight: 900,
    fontSize: 32,
    highlightColor: '#00e5ff',
    highlightMode: 'color',
    strokeWidth: 4.5,
    shadowType: 'hard',
    shadowBlur: 0,
    shadowOpacity: 1,
    shadowDistance: 5,
    activeScale: 1.18,
    maxWordsPerLine: 3,
    transition: 'Zoom Kinetic',
  },
  {
    ...BASE,
    id: 'tiktok_classic',
    category: 'viral',
    name: 'TikTok Classic Pill',
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: 24,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    backgroundColor: '#000000',
    borderStyle: 3,
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    maxWordsPerLine: 5,
    bgPadding: 10,
    bgRadius: 8,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'neon_cyber',
    category: 'viral',
    name: 'Neon Cyber Glow',
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 30,
    color: '#e0f7ff',
    highlightColor: '#ff2bd6',
    highlightMode: 'color',
    strokeWidth: 1.5,
    strokeColor: '#0b0b2a',
    shadowType: 'glow',
    shadowBlur: 24,
    shadowOpacity: 1,
    shadowDistance: 0,
    shadowColor: '#00e5ff',
    letterSpacing: 1.5,
    maxWordsPerLine: 3,
    transition: 'Zoom Kinetic',
  },
  {
    ...BASE,
    id: 'podcast_clean',
    category: 'viral',
    name: 'Podcast Clip Clean',
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 27,
    highlightColor: '#4ade80',
    highlightMode: 'color',
    strokeWidth: 3,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    maxWordsPerLine: 4,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'sports_impact',
    category: 'viral',
    name: 'Sports Impact Italic',
    fontFamily: 'Oswald',
    fontWeight: 700,
    fontSize: 34,
    highlightColor: '#f97316',
    highlightMode: 'color',
    italic: true,
    strokeWidth: 4,
    shadowType: 'hard',
    shadowBlur: 0,
    shadowOpacity: 1,
    shadowDistance: 6,
    shadowColor: '#111111',
    letterSpacing: 1,
    activeScale: 1.2,
    maxWordsPerLine: 3,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'luxe_gold',
    category: 'viral',
    name: 'Luxe Gold Serif',
    fontFamily: 'Playfair Display',
    fontWeight: 900,
    fontSize: 30,
    color: '#f7e7b4',
    highlightColor: '#ffd700',
    highlightMode: 'color',
    strokeWidth: 1,
    strokeColor: '#3b2f0b',
    shadowType: 'glow',
    shadowBlur: 20,
    shadowOpacity: 0.8,
    shadowDistance: 0,
    shadowColor: '#ffb300',
    letterSpacing: 1,
    maxWordsPerLine: 3,
    transition: 'Fade In',
  },

  // ──────────────────────── Pinterest / Aesthetic ────────────────────────
  {
    ...BASE,
    id: 'pinterest_editorial',
    category: 'aesthetic',
    name: 'Editorial Serif Quote',
    fontFamily: 'Playfair Display',
    fontWeight: 900,
    fontSize: 26,
    color: '#fffdf7',
    highlightColor: '#fffdf7',
    highlightMode: 'none',
    italic: true,
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 18,
    shadowOpacity: 0.55,
    shadowDistance: 3,
    textTransform: 'none',
    letterSpacing: 0.5,
    lineHeight: 1.25,
    karaoke: false,
    activeScale: 1,
    maxWordsPerLine: 4,
    yPercent: 50,
    position: 'center',
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'pinterest_wide_caps',
    category: 'aesthetic',
    name: 'Wide Spaced Minimal',
    fontFamily: 'Inter',
    fontWeight: 900,
    fontSize: 20,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 12,
    shadowOpacity: 0.5,
    shadowDistance: 2,
    letterSpacing: 6,
    lineHeight: 1.5,
    karaoke: false,
    activeScale: 1,
    maxWordsPerLine: 3,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'soft_pastel',
    category: 'aesthetic',
    name: 'Soft Pastel Lowercase',
    fontFamily: 'Outfit',
    fontWeight: 900,
    fontSize: 26,
    color: '#fff1f5',
    highlightColor: '#f9a8d4',
    highlightMode: 'color',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 16,
    shadowOpacity: 0.45,
    shadowDistance: 3,
    textTransform: 'lowercase',
    letterSpacing: 0.5,
    lineHeight: 1.2,
    activeScale: 1.08,
    maxWordsPerLine: 4,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'aesthetic_frosted',
    category: 'aesthetic',
    name: 'Frosted Caption Card',
    fontFamily: 'Plus Jakarta Sans',
    fontWeight: 800,
    fontSize: 22,
    color: '#0f172a',
    highlightColor: '#0f172a',
    highlightMode: 'none',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderStyle: 3,
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 18,
    shadowOpacity: 0.4,
    shadowDistance: 4,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    lineHeight: 1.3,
    maxWordsPerLine: 5,
    bgPadding: 14,
    bgRadius: 16,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'vintage_film',
    category: 'aesthetic',
    name: 'Vintage Film Caption',
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 24,
    color: '#f5e9d0',
    highlightColor: '#e8b04b',
    highlightMode: 'color',
    strokeWidth: 1,
    strokeColor: '#2b1d0e',
    shadowType: 'cinematic',
    shadowBlur: 10,
    shadowOpacity: 0.7,
    shadowDistance: 3,
    letterSpacing: 3,
    maxWordsPerLine: 4,
    transition: 'Fade In',
  },
  {
    ...BASE,
    id: 'cinema_minimal',
    category: 'aesthetic',
    name: 'Cinema Clean Minimal',
    fontFamily: 'Outfit',
    fontWeight: 900,
    fontSize: 24,
    color: '#f8fafc',
    highlightColor: '#facc15',
    highlightMode: 'none',
    strokeWidth: 2.5,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.85,
    shadowDistance: 4,
    textTransform: 'none',
    karaoke: false,
    activeScale: 1,
    maxWordsPerLine: 5,
    transition: 'None',
  },

  // ──────────────────── Inverted / Experimental Blends ────────────────────
  // Negative Nano — true per-pixel negative of the footage inside the glyphs,
  // with mask-driven in/out animation. Font, stroke, shadow, glow, pill and
  // transition controls all keep working on it (see NEGATIVE_DEFAULTS).
  {
    ...BASE,
    ...NEGATIVE_DEFAULTS,
    id: 'negative_nano',
    category: 'blend',
    name: 'Negative Nano',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 42,
    xPercent: 50,
    yPercent: 72,
    position: 'custom',
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    karaoke: true,
    activeScale: 1.06,
    letterSpacing: 0.5,
    lineHeight: 1.02,
    maxWordsPerLine: 3,
    transition: 'Fade In + Slide Up',
    variant: 'negative-text',
    inPreset: 'stagger-rise',
    outPreset: 'mask-wipe',
  },
  {
    ...BASE,
    ...NEGATIVE_DEFAULTS,
    id: 'negative_nano_box',
    category: 'blend',
    name: 'Negative Nano · Box',
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 36,
    xPercent: 50,
    yPercent: 72,
    position: 'custom',
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    karaoke: true,
    activeScale: 1.06,
    letterSpacing: 0,
    lineHeight: 1.05,
    maxWordsPerLine: 3,
    bgRadius: 6,
    transition: 'Pop Up',
    variant: 'negative-box',
    inPreset: 'scale-pop',
    outPreset: 'mask-wipe',
  },
  {
    ...BASE,
    ...NEGATIVE_DEFAULTS,
    id: 'negative_nano_karaoke',
    category: 'blend',
    name: 'Negative Nano · Karaoke',
    fontFamily: 'Bebas Neue',
    fontWeight: 400,
    fontSize: 44,
    xPercent: 50,
    yPercent: 72,
    position: 'custom',
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'cinematic',
    shadowBlur: 12,
    shadowOpacity: 0.7,
    shadowDistance: 3,
    karaoke: true,
    activeScale: 1.12,
    letterSpacing: 1,
    lineHeight: 1.0,
    maxWordsPerLine: 3,
    transition: 'Fade In + Slide Up',
    variant: 'negative-highlight',
    inPreset: 'split-word',
    outPreset: 'mask-wipe',
  },
  {
    ...BASE,
    ...NEGATIVE_DEFAULTS,
    id: 'negative_nano_sweep',
    category: 'blend',
    name: 'Negative Nano · Sweep',
    fontFamily: 'Oswald',
    fontWeight: 700,
    fontSize: 40,
    xPercent: 50,
    yPercent: 72,
    position: 'custom',
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    karaoke: false,
    activeScale: 1,
    letterSpacing: 2,
    lineHeight: 1.05,
    maxWordsPerLine: 3,
    transition: 'None',
    variant: 'negative-sweep',
    inPreset: 'none',
    outPreset: 'blur-in',
    inDuration: 0.5,
  },
  {
    ...BASE,
    id: 'inverted_diff',
    category: 'blend',
    name: 'Inverted Pixel Blend',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 34,
    color: '#ffffff',
    highlightColor: '#ffffff',
    highlightMode: 'none',
    mixBlendMode: 'difference',
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    karaoke: false,
    activeScale: 1,
    letterSpacing: 0.5,
    maxWordsPerLine: 3,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'inverted_diff_karaoke',
    category: 'blend',
    name: 'Inverted Blend Karaoke',
    fontFamily: 'Bebas Neue',
    fontWeight: 400,
    fontSize: 38,
    color: '#ffffff',
    highlightColor: '#ffd60a',
    highlightMode: 'color',
    mixBlendMode: 'difference',
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    activeScale: 1.12,
    letterSpacing: 1,
    maxWordsPerLine: 3,
    transition: 'Fade In + Slide Up',
  },
  {
    ...BASE,
    id: 'knockout_box',
    category: 'blend',
    name: 'Knockout Cutout Box',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 32,
    color: '#ffffff',
    highlightColor: '#facc15',
    highlightMode: 'color',
    backgroundColor: '#000000',
    borderStyle: 3,
    strokeWidth: 0,
    shadowType: 'none',
    shadowBlur: 0,
    shadowOpacity: 0,
    shadowDistance: 0,
    maxWordsPerLine: 3,
    bgPadding: 12,
    bgRadius: 4,
    transition: 'Pop Up',
  },
  {
    ...BASE,
    id: 'mirrored_flip',
    category: 'blend',
    name: 'Mirrored / Flipped',
    fontFamily: 'Anton',
    fontWeight: 400,
    fontSize: 30,
    highlightColor: '#facc15',
    highlightMode: 'color',
    flipH: true,
    strokeWidth: 3.5,
    shadowType: 'cinematic',
    shadowBlur: 14,
    shadowOpacity: 0.9,
    shadowDistance: 4,
    maxWordsPerLine: 3,
    transition: 'Pop Up',
  },
];

/** Strips picker-only metadata so applying a template never pollutes styleConfig. */
export function templateToStyle(tpl) {
  const { id: _id, name: _name, category: _category, ...style } = tpl;
  return style;
}

export function hexToRgba(hex, alpha = 1) {
  if (typeof hex !== 'string') return `rgba(0,0,0,${alpha})`;
  const clean = hex.replace('#', '');
  if (clean.length !== 6) return hex;
  const r = parseInt(clean.slice(0, 2), 16);
  const g = parseInt(clean.slice(2, 4), 16);
  const b = parseInt(clean.slice(4, 6), 16);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

export function applyTextTransform(text, transform) {
  const t = text || '';
  if (transform === 'lowercase') return t.toLowerCase();
  if (transform === 'capitalize') return t.replace(/\b\w/g, (ch) => ch.toUpperCase());
  if (transform === 'none') return t;
  return t.toUpperCase();
}

/** CSS `filter` implementing the shadow/glow VFX for a caption block. */
export function buildShadowFilter(style) {
  const type = style.shadowType || 'cinematic';
  const blur = style.shadowBlur ?? 14;
  const dist = style.shadowDistance ?? 4;
  const opacity = style.shadowOpacity ?? 0.9;
  const color = style.shadowColor || '#000000';

  if (type === 'none') return 'none';
  if (type === 'glow') {
    return `drop-shadow(0 0 ${blur}px ${hexToRgba(color, opacity)}) drop-shadow(0 0 ${blur * 1.9}px ${hexToRgba(color, opacity * 0.65)})`;
  }
  if (type === 'hard') {
    return `drop-shadow(${dist}px ${dist}px 0 ${hexToRgba(color, opacity)})`;
  }
  return `drop-shadow(0 ${dist}px ${blur}px ${hexToRgba(color, opacity)}) drop-shadow(0 ${dist * 1.5}px ${blur * 1.6}px ${hexToRgba(color, opacity * 0.6)})`;
}

/**
 * CSS for one word span. `isActive` is the karaoke word currently being spoken,
 * `isKeyword` is a manually pinned emphasis word.
 */
export function buildWordStyle(style, { isActive = false, isKeyword = false } = {}) {
  const mode = style.highlightMode || 'color';
  const emphasised = (isActive && style.karaoke !== false) || isKeyword;
  const strokeWidth = style.strokeWidth ?? 3.5;

  const css = {
    display: 'inline-block',
    color: style.color || '#ffffff',
    fontStyle: style.italic ? 'italic' : 'normal',
    letterSpacing: `${style.letterSpacing ?? 0}px`,
    WebkitTextStroke: strokeWidth > 0 ? `${strokeWidth}px ${style.strokeColor || '#000000'}` : '0',
    paintOrder: 'stroke fill',
    WebkitFontSmoothing: 'antialiased',
    textRendering: 'optimizeLegibility',
    transition: 'transform 90ms ease-out, color 90ms linear',
    transform: 'scale(1)',
  };

  // A font pairing swaps the family on the emphasised word. CSS keeps mixed
  // families on the shared line baseline, so only the glyphs change.
  if (emphasised && style.accentFontFamily && style.accentFontFamily !== style.fontFamily) {
    css.fontFamily = style.accentFontFamily;
  }

  if (!emphasised || mode === 'none') return css;

  if (mode === 'box') {
    css.color = style.highlightTextColor || '#0b0b0b';
    css.backgroundColor = style.highlightBg || '#facc15';
    css.borderRadius = `${style.bgRadius ?? 8}px`;
    css.padding = '0.02em 0.22em';
    css.WebkitTextStroke = '0';
  } else if (mode === 'underline') {
    css.color = style.highlightColor || '#facc15';
    css.boxShadow = `inset 0 -0.16em 0 ${style.highlightBg || style.highlightColor || '#facc15'}`;
  } else {
    css.color = style.highlightColor || '#facc15';
  }

  if (isActive && style.karaoke !== false) {
    css.transform = `scale(${style.activeScale ?? 1.14})`;
  }
  return css;
}

let _measureCtx = null;

/**
 * Font size that fits the widest caption line inside `limitPx` (the 85%
 * caption box), or `fontSize` itself when everything already fits. Never
 * wraps or clips: a caption too wide for the frame is scaled down as one unit.
 * Mirrors fit_shrink() in rendering.py, so the export lands on the same size.
 */
export function fitFontSize(words, style, limitPx) {
  const fontSize = Number(style.fontSize) || 28;
  if (!limitPx || !words?.length || typeof document === 'undefined') return fontSize;
  if (!_measureCtx) _measureCtx = document.createElement('canvas').getContext('2d');
  const ctx = _measureCtx;
  ctx.font = captionFontString(style, fontSize);
  const spacing = Number(style.letterSpacing) || 0;
  let widest = 0;
  for (const line of groupWordsIntoLines(words, style.maxWordsPerLine)) {
    let width = 0;
    for (const w of line) {
      const text = applyTextTransform(typeof w === 'string' ? w : w?.word || '', style.textTransform);
      width += ctx.measureText(text).width + spacing * text.length;
    }
    width += 0.26 * fontSize * Math.max(0, line.length - 1);
    widest = Math.max(widest, width);
  }
  if (widest <= limitPx) return fontSize;
  return Math.max(12, Math.floor(fontSize * (limitPx / widest)));
}

/** Chunks words into fixed-width rows so captions stack like Reels cards. */
export function groupWordsIntoLines(words, maxWordsPerLine) {
  const per = Math.max(1, Number(maxWordsPerLine) || 3);
  const lines = [];
  for (let i = 0; i < words.length; i += per) {
    lines.push(words.slice(i, i + per));
  }
  return lines.length ? lines : [[]];
}
